name: Code Agent Issue Handler
on:
  issues:
    types: [assigned]

jobs:
  process-issue:
    runs-on: ubuntu-latest
    # Only run if issue is assigned to the code agent (replace with your actual agent username)
    if: github.event.issue.assignee.login == 'code-agent-bot'
    permissions:
      contents: write
      issues: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history to create branches

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install @anthropic-ai/sdk @aws-sdk/client-bedrock-runtime

      - name: Configure Git
        run: |
          git config --global user.name "Code Agent Bot"
          git config --global user.email "bot@example.com"

      - name: Process and fix issue
        uses: actions/github-script@v7
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          KNOWLEDGE_BASE_ID: ${{ secrets.KNOWLEDGE_BASE_ID }}
        with:
          script: |
            const { processIssue } = require('./.github/scripts/issue-agent.js');
            
            (async () => {
              try {
                core.info('Starting issue processing...');
                await processIssue({ github, context, core });
                core.info('Issue processing completed successfully.');
              } catch (error) {
                core.error('Issue processing failed: ' + error.message);
                core.setFailed(error.message);
              }
            })(); 